{
 "title": "SkyOrderV2-Health",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "dotnet_build_info" },
   {
    "name": "container",
    "label": "container",
    "query": "All Online Ver2 : masterdata-api-v2|notification-center-v2|skyorder-api-v2,masterdata-api-v2,notification-center-v2,skyorder-api-v2"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Application Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "% CPU consumption",
     "type": "stat",
     "description": "The percentage of available CPU resources consumed.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_working_set_bytes{instance=\"$instance\"}[$__rate_interval] / dotnet_gc_memory_total_available_bytes{instance=\"$instance\"}[$__rate_interval]"
      }
     ]
    },
    {
     "title": "% Paused time",
     "type": "stat",
     "description": "The percentage of time that the application was paused to allow the garbage collector to run.",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dotnet_gc_pause_ratio{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Thread pool queue length",
     "type": "stat",
     "description": "The average length of the thread pool's work queue. Values greater than 0 indicate a problem.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(dotnet_threadpool_queue_length_sum{instance=\"$instance\"}[$__rate_interval]))  / \nsum(rate(dotnet_threadpool_queue_length_count{instance=\"$instance\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Exceptions/ sec",
     "type": "stat",
     "description": "The rate of exceptions being thrown per second",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(dotnet_exceptions_total{instance=\"$instance\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "% Memory consumption",
     "type": "stat",
     "description": "The percentage of available memory resources consumed.",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_working_set_bytes{instance=\"$instance\"} / dotnet_gc_memory_total_available_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "% GC CPU consumption",
     "type": "stat",
     "description": "The percentage of total process CPU utilization that was dedicated to performing garbage collections.",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dotnet_gc_cpu_ratio{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "% JIT CPU consumption",
     "type": "stat",
     "description": "The percentage of CPU utilization that was dedicated to compiling methods by the Just In Time (JIT) compiler.",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dotnet_jit_cpu_ratio{instance=\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage by container V2",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"backend\", pod=~\".*\", image!=\"\", container=~\"$container\", cluster=~\".*\"}[$__rate_interval])) by (container, id)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "CPU Usage % by container V2",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum by (container) (\n    rate(container_cpu_usage_seconds_total{namespace=\"backend\", pod=~\".*\", image!=\"\", container=~\"$container\", cluster=~\".*\"}[$__rate_interval])\n  )\n/\n  sum by (container) (\n    kube_pod_container_resource_limits{namespace=\"backend\", pod=~\".*\", resource=\"cpu\", container=~\"$container\", cluster=~\".*\"}\n  )\n) * 100",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Memory Usage by container V2",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"backend\", pod=~\".*\", image!=\"\", container=~\"$container\", cluster=~\".*\"}) by (container, id)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Memory Usage % by container V2",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum by (container) (\n    container_memory_working_set_bytes{namespace=\"backend\", pod=~\".*\", image!=\"\", container=~\"$container\", cluster=~\".*\"}\n  )\n/\n  sum by (container) (\n    kube_pod_container_resource_limits{namespace=\"backend\", pod=~\".*\", resource=\"memory\", container=~\"$container\", cluster=~\".*\"}\n  )\n) * 100",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Resources by container",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"backend\", pod=~\".*\", resource=\"cpu\", container=~\"$container\", cluster=~\".*\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"backend\", pod=~\".*\", resource=\"cpu\", container=~\"$container\", cluster=~\".*\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"backend\", pod=~\".*\", resource=\"memory\", container=~\"$container\", cluster=~\".*\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"backend\", pod=~\".*\", resource=\"memory\", container=~\"$container\", cluster=~\".*\"}) by (container)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"backend\", pod=~\".*\", image!=\"\", container=~\"$container\", cluster=~\".*\"}[$__rate_interval])) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"backend\", pod=~\".*\", image!=\"\", container=~\"$container\", cluster=~\".*\"}) by (container)"
    }
   ]
  },
  {
   "title": "Memory / Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory use",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_working_set_bytes{instance=\"$instance\"}",
       "legendFormat": "# bytes (in physical memory)"
      },
      {
       "expr": "dotnet_gc_memory_total_available_bytes{instance=\"$instance\"}",
       "legendFormat": "Total bytes available (memory limit)"
      }
     ]
    },
    {
     "title": "Heap size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "dotnet_gc_heap_size_bytes{instance=\"$instance\"}[$__rate_interval]",
       "legendFormat": "gen {{gc_generation}}"
      }
     ]
    },
    {
     "title": "GC CPU + pause ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "dotnet_gc_cpu_ratio{instance=\"$instance\"}",
       "legendFormat": "GC CPU %"
      },
      {
       "expr": "dotnet_gc_pause_ratio{instance=\"$instance\"}",
       "legendFormat": "GC Pause %"
      }
     ]
    },
    {
     "title": "Number of GC collections/ sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(dotnet_gc_collection_count_total{instance=\"$instance\"}[$__interval])) by (gc_generation, gc_reason)",
       "legendFormat": "gen {{gc_generation}}: {{gc_reason}}"
      }
     ]
    },
    {
     "title": "Bytes allocated (by heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(dotnet_gc_allocated_bytes_total{instance=\"$instance\"}[$__interval])) by (gc_heap)",
       "legendFormat": "Alloc bytes {{gc_heap}}"
      }
     ]
    },
    {
     "title": "Average GC duration (by generation)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(dotnet_gc_collection_seconds_sum{instance=\"$instance\"}[$__interval])) by (gc_generation) / sum(increase(dotnet_gc_collection_seconds_count{instance=\"$instance\"}[$__interval])) by (gc_generation) ",
       "legendFormat": "{{gc_generation}}"
      }
     ]
    },
    {
     "title": "GC duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sum(increase(dotnet_gc_collection_seconds_bucket{instance=\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread pool queue length",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum by (le) (increase(dotnet_threadpool_queue_length_bucket{instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Num thread pool threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "dotnet_threadpool_num_threads{instance=\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Thread pool adjustment reasons",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum(increase(dotnet_threadpool_adjustments_total{instance=\"$instance\"}[$__interval])) by (adjustment_reason )",
       "legendFormat": "{{adjustment_reason}}"
      }
     ]
    },
    {
     "title": "Num thread timers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "dotnet_threadpool_timer_count{instance=\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JIT compliation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Methods compiled/ sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "rate(dotnet_jit_method_total{instance=\"$instance\"}[$__interval])",
       "legendFormat": "Dynamic methods"
      },
      {
       "expr": "rate(dotnet_jit_method_total{dynamic=\"false\", instance=\"$instance\"}[$__interval])",
       "legendFormat": "Methods"
      }
     ]
    },
    {
     "title": "JIT CPU usage ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "dotnet_jit_cpu_ratio{instance=\"$instance\"}",
       "legendFormat": "% CPU utilization"
      }
     ]
    }
   ]
  },
  {
   "title": "Contention",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Locks contended/ sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "rate(dotnet_contention_total{instance=\"$instance\"}[$__interval])",
       "legendFormat": "# Locks contended"
      }
     ]
    },
    {
     "title": "Time waiting for locks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "increase(dotnet_contention_seconds_total{instance=\"$instance\"}[$__interval])",
       "legendFormat": "Waiting time"
      }
     ]
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exceptions/ sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "rate(dotnet_exceptions_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sockets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes sent vs received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "rate(dotnet_sockets_bytes_received_total[$__rate_interval])",
       "legendFormat": "Received/ sec"
      },
      {
       "expr": "rate(dotnet_sockets_bytes_sent_total[$__rate_interval])",
       "legendFormat": "Sent/ sec"
      }
     ]
    },
    {
     "title": "Connections established",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "increase(dotnet_sockets_connections_established_incoming_total[$__rate_interval])",
       "legendFormat": "Incoming "
      },
      {
       "expr": "increase(dotnet_sockets_connections_established_outgoing_total[$__rate_interval])",
       "legendFormat": "Outgoing"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread Diagnostics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads consuming CPU",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(skyorder_thread_cpu_seconds_total[$__interval]) * on(thread_id, thread_label) group_left(thread_state) skyorder_thread_info{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Largest CPU threads (1m)",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, rate(skyorder_thread_cpu_seconds_total[1m]) * on(thread_id, thread_label) group_left(thread_state) skyorder_thread_info{instance=\"$instance\"})"
      }
     ]
    }
   ]
  }
 ]
}